### ISSUE TITLE
Improve ulib.c

### ISSUE THREAD

**Issue by TroyMitchell911** [TroyMitchell911/caffeinix#10]
You can look for some empty functions in ulib.c to implement them.

**Comment by TroyMitchell911** [comment]
@GoKo-Son626

**Comment by GoKo-Son626** [comment]
[cace710](https://github.com/TroyMitchell911/caffeinix/pull/19/commits/cace7105ad76e62cb6c129f6106be64ecd5b3ac4)

**Comment by GoKo-Son626** [comment]
Fixed a indentation problem
https://github.com/TroyMitchell911/caffeinix/commit/a4bdf7249768fc16a3cb458ddb197d34b8ed2942

**Comment by TroyMitchell911** [comment]
#19
