### ISSUE TITLE
Fix the format problem of umalloc.c

### ISSUE THREAD

**Issue by TroyMitchell911** [TroyMitchell911/caffeinix#16]
This file was copied from xv6 and only modified a little, but the format was not changed to caffeinix format.

**Comment by GoKo-Son626** [comment]
Changed the "umalloc.c" format to the caffeinix format  #19

**Comment by GoKo-Son626** [comment]
[Changed the "mkfs.c" file format](https://github.com/TroyMitchell911/caffeinix/pull/19/commits/0e3772973bf28601917829bed20f448a74e3aba8)

**Comment by GoKo-Son626** [comment]
[cace710]
(https://github.com/TroyMitchell911/caffeinix/pull/19/commits/cace7105ad76e62cb6c129f6106be64ecd5b3ac4)

**Comment by GoKo-Son626** [comment]
Fixed a indentation problem
_a4bdf7249768fc16a3cb458ddb197d34b8ed2942
